CREATE TABLE DIA_DA_SEMANA (
	ID INT NOT NULL PRIMARY KEY,
  DIA INT NOT NULL,
  DIA_NOME VARCHAR(15) NOT NULL,
  DIA_CODIGO VARCHAR(15) NOT NULL
);

INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 1, 'Domingo', 'DOMINGO');
INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 2, 'Segunda-feira', 'SEGUNDA_FEIRA');
INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 3, 'Terça-feira', 'TERCA_FEIRA');
INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 4, 'Quarta-feira', 'QUARTA_FEIRA');
INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 5, 'Quinta-feira', 'QUINTA_FEIRA');
INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 6, 'Sexta-feira', 'SEXTA_FEIRA');
INSERT INTO DIA_DA_SEMANA (ID, DIA, DIA_NOME, DIA_CODIGO) (SELECT NEXTVAL('hibernate_sequence'), 7, 'Sábado', 'SABADO');

DELETE FROM HORARIO;

ALTER TABLE HORARIO ADD FK_DIA_DA_SEMANA INT NOT NULL;
ALTER TABLE HORARIO ADD CONSTRAINT FK_DIA_DA_SEMANA_ID FOREIGN KEY (FK_DIA_DA_SEMANA) REFERENCES DIA_DA_SEMANA (ID);
