CREATE TABLE ENDERECO (
	ID INT NOT NULL PRIMARY KEY,
    ESTADO VARCHAR(120) NOT NULL,
    CIDADE VARCHAR(120) NOT NULL,
    BAIRRO VARCHAR(120) NOT NULL,
    RUA VARCHAR(120) NOT NULL,
    NUMERO_RUA VARCHAR(120) NOT NULL,
    CEP VARCHAR(20) NOT NULL,
    COMPLEMENTO VARCHAR(20),
    DATA_CADASTRO TIMESTAMP NOT NULL,
    FK_EMPRESA INT NOT NULL
);

ALTER TABLE ENDERECO ADD CONSTRAINT FK_EMPRESA_ID FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA (ID);
