CREATE TABLE SERVICO (
	ID INT NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR(120) NOT NULL,
    PRECO FLOAT NOT NULL,
    FK_EMPRESA INT NOT NULL
);

ALTER TABLE SERVICO ADD CONSTRAINT FK_EMPRESA_ID FOREIGN KEY (FK_EMPRESA) REFERENCES EMPRESA (ID);

CREATE TABLE AGENDA_SERVICOS (
    FK_AGENDA INT NOT NULL,
    FK_SERVICO INT NOT NULL
);

ALTER TABLE AGENDA_SERVICOS ADD CONSTRAINT FK_AGENDA_ID FOREIGN KEY (FK_AGENDA) REFERENCES AGENDA (ID);
ALTER TABLE AGENDA_SERVICOS ADD CONSTRAINT FK_SERVICO_ID FOREIGN KEY (FK_SERVICO) REFERENCES SERVICO (ID);

ALTER TABLE AGENDA DROP COLUMN DESCRICAO_SERVICO;
ALTER TABLE AGENDA DROP COLUMN PRECO;
ALTER TABLE AGENDA ADD TOTAL FLOAT NOT NULL;
