UPDATE DIA_DA_SEMANA SET DIA = 0 WHERE DIA_CODIGO = 'SEGUNDA_FEIRA';
UPDATE DIA_DA_SEMANA SET DIA = 1 WHERE DIA_CODIGO = 'TERCA_FEIRA';
UPDATE DIA_DA_SEMANA SET DIA = 2 WHERE DIA_CODIGO = 'QUARTA_FEIRA';
UPDATE DIA_DA_SEMANA SET DIA = 3 WHERE DIA_CODIGO = 'QUINTA_FEIRA';
UPDATE DIA_DA_SEMANA SET DIA = 4 WHERE DIA_CODIGO = 'SEXTA_FEIRA';
UPDATE DIA_DA_SEMANA SET DIA = 5 WHERE DIA_CODIGO = 'SABADO';
UPDATE DIA_DA_SEMANA SET DIA = 6 WHERE DIA_CODIGO = 'DOMINGO';
